name: get price

on:
  schedule:
  - cron: '30 21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: "projects/169411888623/locations/global/workloadIdentityPools/github-tracker/providers/github"
        service_account: "domcronjob@redtracker-418718.iam.gserviceaccount.com"
        token_format: 'access_token'
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12'
    - name: install python packages
      run:
        pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib google-auth
    - name: call av api
      env:
        AV_KEY: ${{ secrets.AV_API_KEY }}
      run: python ./backend/av_api.py
